import matplotlib.pyplot as plt
import numpy as np

english_means = [0.08167,0.01492,0.02782,0.04253,0.12702,0.02228,0.02015,0.06094,0.06966,0.00153,0.00772,0.04025,0.02406,0.06749,0.07507,0.01929,0.00095,0.05987,0.06327,0.09056,0.02758,0.00978,0.02360,0.00150,0.01974,0.00074]
alphabet = list("ABCDEFGHIJKLMNOPQRSTUVWXYZ")

message = ("OUEVE BEKCO AAFEO ITIBE HIAKU TNOTQ DRHKR ITEIH AEGOJ ARSHN TTEES TAOMO SEODU EDTWM GTCWO CCWDE TFAEI EHIOI CIATC HFLNN OKNIA TVIOU ADTUA ATTRO AHWNF ASHLD IIESE TTTLR OMWTF IEAOY ALARM YAHUH AKKWI NLDTE NNKYL DTABW WNOIO NIRIS HBAHO GNMNU KLKEE GTSEI EATRH IGLTE NSDAR FHAIL WNIEW DBIBN RATUN FANTC YRHEA ERAST MTHUC ASEVG SIMOS IEETE DMEOR GDONE SBPTM ETREU AAVTC WATNE DTENO UTTTE FETEH EEWAT MTHRT BEHAA YSABA NTWOR DABSA LSNYP IIBNA SYWLE KSDTA TTOEE OSHTS HETLL EAWAT WHEOO VIFDB NOTUS OAEWH LEUVN ETEAA ODMRU DYHNR EHNVR ETATG HDAHT HEEOR SONOR EUEBE PIIDT NZSHS LEERP HNCDL OHOGO HUOTA TAVTG FWDDA TUIDE NNEHH IATTC RIHNO EDWOD VTLDN NDSBA IAIEI OILNT EMIRY TTEYT STHIR KWCUT LBHSE BADNT AERTI EAEAE WDACN AKSEU TEBAA BAETT STDMH TTARF YNYHN EFHSG EYUSS OSLNI NEIAD ARAWW HIADO DKTRZ CUANI TIEUH AETSN OTAIO NOTAD LRROE FIFDA MOTHE TAONR UIALT YEDLH UXTEL LNTTW TWSGV BEHOT IAIEO AFAOE AEOFN SCHNL EBNFS DTTEN FHGOO RAEEM TDTEC OVNDT KXTOA IFOAU REDOM NSEII TSUIR PBIED AYTCH HLNRU ANNWB HTITK OEUOT WGWTR HDSTS QIMEA HASEE LKRIS UNIII TAATD HSHIN HERWH ONPLE KTDAE RODIE PDAFE TLETP IRGII CCGYT EEAEN RINNH TICIS CSRNA NNHEA LLTCH IEOFD ILEMO YEKEH DRSIB NILSE TATDP EWNDR VHFAE EERNL HERNE IYTTD TDYSO IEUET OAUAF IAHID DHGNT YNNTN TGEFI LOTTW OTEPH NLWIV ERWKH ARTGE DTHEN EOONA DBHOU OTEEE TNEHK LRNOA DNNHI TBAEO TEGTN TMGTI HKAEE ICNID OMXEI LOOEE TDLTP YAPDS HDFNE ATARF CITBR UETSE EIDUI NHBEL TLGAL FCMIA TAOOE IDTSG KDHEH TCEDT ISAHI IPJBE OOAWO UIUON NNWWT CUTSU ROAMT KOOOH TIHHL RMBDI EDYUO EAAMO SYNES DLIHI TTETR TEGTE AESBL HELSK SNSIJ OLNAA WSSTE GSTUS EADMG ATINI EESPB TMHOT IWADD TEAST AATHL AHLGS ETNAL EPDAD NISUL ENUGW VAWTD NORLI OCCHN ENAOT ISICS IMTEH ADGKA FMION AERIN TGTES OTHOO IIRHA").replace(" ", "").upper()
letter_frequencies = [1 for i in range(26)]

for i in range(len(message)):
    index = alphabet.index(message[i])
    letter_frequencies[index] += 1

ciphertext_means = [((letter_frequencies[i])/len(message)) for i in range(26)]

N = 26

ind = np.arange(N) 
width = 0.35       
plt.bar(ind, ciphertext_means, width, label='Cipher Text')
plt.bar(ind + width, english_means, width,
    label='English')

plt.ylabel('Frequencies')
plt.title('Frequency Analysis')

plt.xticks(ind + width / 2, (alphabet[i]for i in range(len(alphabet))))
plt.legend(loc='best')
plt.show()